# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgsql-db-volume:/var/lib/postgresql/data

  dbtest:
    image: postgres:13-alpine
    ports:
      - 54322:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: snooker_test
    volumes:
      - test-db-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  test-db-volume:
    external: false
  pgsql-db-volume:
    external: false
